package(default_visibility = ["//visibility:public"])

py_library(
    name = "hlo_py",
    srcs = [
        "optimize.py",
        "instruction.py",
    ],
    deps = [
        "//tensorflow/neuron/python:utils_py",
    ],
)
